baseURL = 'https://fredthomsen.net/'
languageCode = 'en-us'
title = 'Fred Thomsen'

[module]
  [[module.imports]]
    path = 'github.com/adityatelange/hugo-PaperMod'

[markup.goldmark.renderer]
unsafe = true

[params]
defaultTheme = 'dark'
ShowShareButtons = false
ShowReadingTime = false
ShowCodeCopyButtons = true
ShowFullTextinRSS = true
ShowBreadCrumbs = false
ShowPostNavLinks = false
enableRobotsTXT = true
disableThemeToggle = true

[params.label]
text = ''

[params.homeInfoParams]
Title = 'Fred Thomsen'
Content = 'Engineer/Grappler/Metalhead/Swede/All-Around Nerd'

[[params.socialIcons]]
name = 'email'
url = 'mailto:fae4wtf2f23r.bc9z4@passmail.net'
[[params.socialIcons]]
name = 'linkedin'
url = 'https://www.linkedin.com/in/fredthomsen'
[[params.socialIcons]]
name = 'github'
url = 'https://github.com/fredthomsen'

[params.profileMode]
enabled = true
title = 'Fred Thomsen'
imageUrl = 'https://fredthomsen-website-content.s3.amazonaws.com/images/swedenstare.png'
imageWidth = 250
imageHeight = 250
imageTitle = 'Fred Thomsen'
